# This jupyter notebook file aims to scale our features in accordance with standard practices, i.e. fitting a scaler to the training data and applying that fitted scaler on both training and test data

In [1]:
import pandas as pd 
from sklearn.preprocessing import StandardScaler

In [3]:
# Loading datasets
df_train = pd.read_csv("../../data/claims_train_final.csv")
df_test = pd.read_csv("../../data/claims_test_final.csv")
df_train

,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,0,0.43,7,18,36,95,B1,Regular,1054,R24
1,0,0.10,7,17,80,95,B2,Regular,598,R25
2,0,0.33,7,3,36,76,B6,Regular,4172,R82
3,0,0.56,5,4,73,52,B13,Diesel,15,R24
4,0,0.27,8,0,37,50,B11,Diesel,3021,R53
...,...,...,...,...,...,...,...,...,...,...
541011,0,0.20,6,10,32,76,B2,Diesel,1314,R24
541012,0,0.06,10,14,34,60,B5,Diesel,685,R72
541013,0,0.34,6,8,32,95,B5,Diesel,242,R82
541014,0,0.72,9,7,39,72,B2,Regular,3301,R73
541015,0,0.59,7,18,41,106,B1,Regular,26,R24

In [4]:
df_test

,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,0,1.00,5,8,46,50,B1,Regular,4116,R24
1,0,0.24,4,10,46,64,B1,Regular,1329,R11
2,0,0.41,4,0,32,72,B12,Regular,377,R73
3,0,0.07,5,4,57,50,B2,Diesel,251,R93
4,0,0.06,4,10,45,50,B2,Regular,94,R53
...,...,...,...,...,...,...,...,...,...,...
135598,0,0.35,10,6,57,85,B12,Diesel,879,R82
135599,0,0.87,10,10,46,56,B5,Diesel,1609,R11
135600,0,1.00,8,8,35,50,B5,Regular,3744,R93
135601,0,0.50,11,1,32,54,B12,Regular,6485,R11
135602,0,0.41,5,2,56,50,B1,Regular,182,R82

In [5]:
# We need to scale each of the four following features: VehPower, VehAge, DrivAge, BonusMalus (and maybe density if we keep it, will do it for now and might remove later)

# VehPower
scalerVehPower = StandardScaler() 
trainingVehPower = df_train[["VehPower"]]
scalerVehPower.fit(trainingVehPower)
df_train["VehPower"] = scalerVehPower.transform(trainingVehPower)
testVehPower = df_test[["VehPower"]]
df_test["VehPower"] = scalerVehPower.transform(testVehPower)


print(df_train["VehPower"].describe().round(2))
print(df_test["VehPower"].describe().round(2))

# VehAge
scalerVehAge = StandardScaler() 
trainingVehAge = df_train[["VehAge"]]
scalerVehAge.fit(trainingVehAge)
df_train["VehAge"] = scalerVehAge.transform(trainingVehAge)
testVehAge = df_test[["VehAge"]]
df_test["VehAge"] = scalerVehAge.transform(testVehAge)


print(df_train["VehAge"].describe().round(2))
print(df_test["VehAge"].describe().round(2))


# DrivAge
scalerDrivAge = StandardScaler() 
trainingDrivAge = df_train[["DrivAge"]]
scalerDrivAge.fit(trainingDrivAge)
df_train["DrivAge"] = scalerDrivAge.transform(trainingDrivAge)
testDrivAge = df_test[["DrivAge"]]
df_test["DrivAge"] = scalerDrivAge.transform(testDrivAge)


print(df_train["DrivAge"].describe().round(2))
print(df_test["DrivAge"].describe().round(2))


# BonusMalus
scalerBonusMalus = StandardScaler() 
trainingBonusMalus = df_train[["BonusMalus"]]
scalerBonusMalus.fit(trainingBonusMalus)
df_train["BonusMalus"] = scalerBonusMalus.transform(trainingBonusMalus)
testBonusMalus = df_test[["BonusMalus"]]
df_test["BonusMalus"] = scalerBonusMalus.transform(testBonusMalus)


print(df_train["BonusMalus"].describe().round(2))
print(df_test["BonusMalus"].describe().round(2))

# As expected we see vehpower with the same min and max due to them not being cleaned and having the same range, while we see different min/max values for the other three features


# Density (for now)
scalerDensity = StandardScaler() 
trainingDensity = df_train[["Density"]]
scalerDensity.fit(trainingDensity)
df_train["Density"] = scalerDensity.transform(trainingDensity)
testDensity = df_test[["Density"]]
df_test["Density"] = scalerDensity.transform(testDensity)


print(df_train["Density"].describe().round(2))
print(df_test["Density"].describe().round(2))

count    541016.00
mean          0.00
std           1.00
min          -1.20
25%          -0.71
50%          -0.22
75%           0.27
max           4.17
Name: VehPower, dtype: float64
count    135603.00
mean          0.00
std           1.00
min          -1.20
25%          -0.71
50%          -0.22
75%           0.27
max           4.17
Name: VehPower, dtype: float64
count    541016.00
mean         -0.00
std           1.00
min          -1.26
25%          -0.90
50%          -0.18
75%           0.72
max           5.93
Name: VehAge, dtype: float64
count    135603.00
mean          0.00
std           1.02
min          -1.26
25%          -0.90
50%          -0.18
75%           0.72
max          16.73
Name: VehAge, dtype: float64
count    541016.00
mean          0.00
std           1.00
min          -1.95
25%          -0.81
50%          -0.11
75%           0.67
max           3.30
Name: DrivAge, dtype: float64
count    135603.00
mean         -0.00
std           1.00
min          -1.95
25%          -0.81
50%          -0.11
75%           0.67
max           3.86
Name: DrivAge, dtype: float64
count    541016.00
mean         -0.00
std           1.00
min          -0.63
25%          -0.63
50%          -0.63
75%           0.27
max           6.30
Name: BonusMalus, dtype: float64
count    135603.00
mean          0.00
std           1.00
min          -0.63
25%          -0.63
50%          -0.63
75%           0.27
max           8.35
Name: BonusMalus, dtype: float64
count    541016.00
mean         -0.00
std           1.00
min          -0.45
25%          -0.43
50%          -0.35
75%          -0.03
max           6.36
Name: Density, dtype: float64
count    135603.00
mean         -0.00
std           0.99
min          -0.45
25%          -0.43
50%          -0.35
75%          -0.04
max           6.36
Name: Density, dtype: float64

In [6]:
df_train

,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,0,0.43,0.266880,1.974647,-0.672262,2.259081,B1,Regular,-0.187042,R24
1,0,0.10,0.266880,1.794735,2.445658,2.259081,B2,Regular,-0.302036,R25
2,0,0.33,0.266880,-0.724035,-0.672262,1.041179,B6,Regular,0.599254,R82
3,0,0.56,-0.708699,-0.544123,1.949625,-0.497224,B13,Diesel,-0.449057,R24
4,0,0.27,0.754669,-1.263772,-0.601401,-0.625424,B11,Diesel,0.308995,R53
...,...,...,...,...,...,...,...,...,...,...
541011,0,0.20,-0.220910,0.535350,-0.955710,1.041179,B2,Diesel,-0.121476,R24
541012,0,0.06,1.730248,1.254998,-0.813986,0.015577,B5,Diesel,-0.280097,R72
541013,0,0.34,-0.220910,0.175526,-0.955710,2.259081,B5,Diesel,-0.391812,R82
541014,0,0.72,1.242458,-0.004387,-0.459677,0.784778,B2,Regular,0.379606,R73
541015,0,0.59,0.266880,1.974647,-0.317953,2.964182,B1,Regular,-0.446283,R24

In [7]:
df_test

,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,0,1.00,-0.708699,0.175526,0.036356,-0.625424,B1,Regular,0.585132,R24
1,0,0.24,-1.196488,0.535350,0.036356,0.271977,B1,Regular,-0.117693,R11
2,0,0.41,-1.196488,-1.263772,-0.955710,0.784778,B12,Regular,-0.357768,R73
3,0,0.07,-0.708699,-0.544123,0.815836,-0.625424,B2,Diesel,-0.389543,R93
4,0,0.06,-1.196488,0.535350,-0.034506,-0.625424,B2,Regular,-0.429135,R53
...,...,...,...,...,...,...,...,...,...,...
135598,0,0.35,1.730248,-0.184299,0.815836,1.618080,B12,Diesel,-0.231174,R82
135599,0,0.87,1.730248,0.535350,0.036356,-0.240823,B5,Diesel,-0.047083,R11
135600,0,1.00,0.754669,0.175526,-0.743124,-0.625424,B5,Regular,0.491321,R93
135601,0,0.50,2.218037,-1.083859,-0.955710,-0.369024,B12,Regular,1.182546,R11
135602,0,0.41,-0.708699,-0.903947,0.744974,-0.625424,B1,Regular,-0.406943,R82

In [8]:
# Exporting the new dataframes to csv files
df_train.to_csv("../../data/claims_train_scaled.csv", index=False)
df_test.to_csv("../../data/claims_test_final.csv", index=False)